{% set name = "knnimpute" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/knnimpute-{{ version }}.tar.gz
  sha256: 4a05857be4b883a6d690c4c9e07e2920b324c30c97b7ed6241e0bdfb0bcb7af0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pypandoc
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy >=1.10
    - six

test:
  imports:
    - knnimpute
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hammerlab/knnimpute
  summary: k-Nearest Neighbor imputation
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Multiple implementations of kNN imputation in pure Python + NumPy.

    PyPI: [https://pypi.org/project/knnimpute/](https://pypi.org/project/knnimpute/)

  doc_url: https://github.com/hammerlab/knnimpute
  dev_url: https://github.com/hammerlab/knnimpute

extra:
  recipe-maintainers:
    - sugatoray
